// Generated by CoffeeScript 1.10.0
var app;

app = angular.module('Todo', []);

app.controller('TodoController', function($scope) {
  $scope.tasks = [];
  $scope.task = {};
  return $scope.addTask = function(task) {
    if (Object.keys(task).length) {
      task.done = false;
      task.added = new Date;
      $scope.tasks.push(task);
    }
    return $scope.task = {};
  };
});
