// Generated by CoffeeScript 1.10.0
var app, old;

app = angular.module('Todo', []);

old = {
  name: 'old one',
  done: false,
  added: moment('1992-06-14').fromNow()
};

app.controller('TodoController', function($scope, $filter) {
  $scope.tasks = [old];
  $scope.task = {};
  $scope.incompleteTasks = function() {
    return $filter('filter')($scope.tasks, {
      done: false
    }).length;
  };
  $scope.addTask = function(task) {
    if (Object.keys(task).length) {
      task.added = moment().fromNow();
      task.done = false;
      $scope.tasks.push(task);
    }
    return $scope.task = {};
  };
  $scope.taskComplete = function(task) {
    return task.done = !task.done;
  };
  $scope.taskClear = function(task) {
    return $scope.tasks.splice($scope.tasks.indexOf(task), 1);
  };
  return $scope.clearCompleted = function() {
    return $scope.tasks = $scope.tasks.filter(function(task) {
      return !task.done;
    });
  };
});
