// Generated by CoffeeScript 1.10.0
var app;

app = angular.module('Todo', []);

app.controller('TodoController', function($scope, $filter, $http) {
  $scope.task = {};
  $scope.tasks = [];
  $http.get('/api/tasks').success(function(tasks) {
    return $scope.tasks = tasks;
  }).error(function(error) {
    return console.log(error);
  });
  $scope.incompleteTasks = function() {
    var inc;
    inc = 0;
    $scope.tasks.map(function(task) {
      if (!task.done) {
        return ++inc;
      }
    });
    return inc;
  };
  $scope.addTask = function(task) {
    if (task.name) {
      $http.post('/api/tasks', task).success(function(task) {
        return $scope.tasks.push(task);
      }).error(function(error) {
        return console.log(error);
      });
    }
    return $scope.task = {};
  };
  $scope.toggleComplete = function(task) {
    var index;
    index = $scope.tasks.indexOf(task);
    return $http.put('/api/tasks/' + task._id).success(function(task) {
      return $scope.tasks.splice(index, 1, task);
    }).error(function(error) {
      return console.log(error);
    });
  };
  $scope.clearTask = function(task) {
    var index;
    index = $scope.tasks.indexOf(task);
    return $http["delete"]('/api/tasks/' + task._id).success(function() {
      return $scope.tasks.splice(index, 1);
    }).error(function(error) {
      return console.log(error);
    });
  };
  return $scope.clearCompleted = function() {
    return $http["delete"]('/api/tasks').success(function(tasks) {
      return $scope.tasks = tasks;
    });
  };
});
