// Generated by CoffeeScript 1.10.0
var app, express, path;

express = require('express');

path = require('path');

app = express();

app.set('port', 3000);

app.set('views', path.join('client', 'views'));

app.set('view engine', 'jade');

app.get('/', function(req, res) {
  return res.render('index');
});

app.listen(app.get('port'), console.log('listening at ' + app.get('port')));
